<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Information about your organization is used to generate security certificates and other software defaults.';
$lang['organization_app_name'] = 'Samahan';
$lang['organization_city'] = 'Lungsod';
$lang['organization_city_invalid'] = 'Hindi tumpak ang Lungsod.';
$lang['organization_country'] = 'Bansa';
$lang['organization_country_invalid'] = 'Hindi tumpak ang Lungsod.';
$lang['organization_organization'] = 'Samahan';
$lang['organization_organization'] = 'Samahan';
$lang['organization_organization_invalid'] = 'Hindi tumpak ang Samahan.';
$lang['organization_postal_code'] = 'Postal/Zip Code';
$lang['organization_postal_code_invalid'] = 'Postal code is invalid.';
$lang['organization_region'] = 'Probinsiya';
$lang['organization_region_invalid'] = 'Hindi tumpak ang purok.';
$lang['organization_street_address'] = 'Lansangan';
$lang['organization_street_address_invalid'] = 'Hindi tumpak ang Lansangan.';
$lang['organization_unit'] = 'Unit';
$lang['organization_unit_invalid'] = 'Hindi tumpak ang Lungsod.';
