<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = '贵组织的信息将用来生成安全认证和软件默认值';
$lang['organization_app_name'] = '组织';
$lang['organization_city'] = '城市';
$lang['organization_city_invalid'] = '城市名无效';
$lang['organization_country'] = '国家';
$lang['organization_country_invalid'] = '国家名无效';
$lang['organization_organization'] = '组织';
$lang['organization_organization'] = '组织';
$lang['organization_organization_invalid'] = '组织名无效';
$lang['organization_postal_code'] = '邮政编码';
$lang['organization_postal_code_invalid'] = '邮政编码无效';
$lang['organization_region'] = '省';
$lang['organization_region_invalid'] = '地区名无效';
$lang['organization_street_address'] = '街道地址';
$lang['organization_street_address_invalid'] = '街道地址无效';
$lang['organization_unit'] = '单位';
$lang['organization_unit_invalid'] = '单位无效';
