<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Information about your organization is used to generate security certificates and other software defaults.';
$lang['organization_app_name'] = 'Organization';
$lang['organization_city'] = '城市';
$lang['organization_city_invalid'] = 'City is invalid.';
$lang['organization_country'] = '国家';
$lang['organization_country_invalid'] = 'Country is invalid.';
$lang['organization_organization'] = '组织';
$lang['organization_organization'] = '组织';
$lang['organization_organization_invalid'] = 'Organization is invalid.';
$lang['organization_postal_code'] = 'Postal/Zip Code';
$lang['organization_postal_code_invalid'] = 'Postal code is invalid.';
$lang['organization_region'] = 'State/Province';
$lang['organization_region_invalid'] = 'Region is invalid.';
$lang['organization_street_address'] = 'Street Address';
$lang['organization_street_address_invalid'] = 'Street address is invalid.';
$lang['organization_unit'] = 'Unit';
$lang['organization_unit_invalid'] = 'Unit is invalid.';
