<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'To oprogramowanie oferuje wiele ró?nych wersji j?zykowych.  U?yj tego narz?dzia aby zmieni? domy?lny j?zyk systemowy.';
$lang['language_app_name'] = 'Język';
$lang['language_default_system_language'] = 'Domyślny język systemowy';
$lang['language_keyboard'] = 'Klawiatura';
$lang['language_keyboard_is_invalid'] = 'Podany typ klawiatury jest nieprawid?owy.';
$lang['language_language'] = 'Język';
$lang['language_language_is_invalid'] = 'Podany język jest nieprawidłowy';
$lang['language_update_my_login_session'] = 'Aktualizuj moją sesję logowania';
