<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = '时区和时钟同步工具';
$lang['date_app_name'] = '日期和时间';
$lang['date_app_tooltip'] = 'VoIP，验证服务和其他应用需要正确的时间设置，请确保时区和时间正确。';
$lang['date_date'] = '日期';
$lang['date_synchronization_changed_time_by_x_seconds:'] = '此同步用下面的秒数更改系统时间。';
$lang['date_synchronize_now'] = '现在同步';
$lang['date_time'] = '时间';
$lang['date_time_server'] = '时间服务器';
$lang['date_time_server_is_invalid'] = '时间服务器无效';
$lang['date_time_synchronization_schedule_is_invalid'] = '时间同步调度无效';
$lang['date_time_zone'] = '时区';
$lang['date_time_zone_is_invalid'] = '时区无效';
