<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Information om din organisation används för att generera certifikat och andra mjukvaruinställningar.';
$lang['organization_app_name'] = 'Organisation';
$lang['organization_city'] = 'Stad';
$lang['organization_city_invalid'] = 'Staden är ogiltig.';
$lang['organization_country'] = 'Land';
$lang['organization_country_invalid'] = 'Landet är ogiltigt.';
$lang['organization_organization'] = 'Organisation';
$lang['organization_organization'] = 'Organization';
$lang['organization_organization_invalid'] = 'Organisationen är ogiltig.';
$lang['organization_postal_code'] = 'Postnummer';
$lang['organization_postal_code_invalid'] = 'Postnumret är ogiltigt.';
$lang['organization_region'] = 'Land';
$lang['organization_region_invalid'] = 'Regionen är ogiltig.';
$lang['organization_street_address'] = 'Gatuadress';
$lang['organization_street_address_invalid'] = 'Gatuadressen är ogiltig.';
$lang['organization_unit'] = 'Avdelning';
$lang['organization_unit_invalid'] = 'Avdelning är ogiltig.';
