<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'Een antivirus gateway biedt bescherming op uw netwerk en server.';
$lang['antivirus_app_name'] = 'Antivirus gateway';
$lang['antivirus_app_tooltip'] = 'Versleutelde bestanden worden vaak gebruikt om malware te leveren, dus wees voorzichtig met het toestaan ​​van dit soort bestanden via de antivirus motor.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Block encrypted archive value is invalid.';
$lang['antivirus_block_encrypted_files'] = 'Blokkeer versleutelde bestanden.';
$lang['antivirus_every_two_hours'] = 'Elke twee uur';
$lang['antivirus_maximum_file_size'] = 'De maximale bestandsgrootte in een zip-bestanden.';
$lang['antivirus_maximum_file_size_invalid'] = 'Ongeldige maximale bestandsgrootte.';
$lang['antivirus_maximum_files'] = 'Het maximaal aantal bestanden in een Zip-bestanden.';
$lang['antivirus_maximum_files_invalid'] = 'Ongeldig maximaal aantal bestanden.';
$lang['antivirus_maximum_recursion'] = 'De maximale recursie in zip-bestanden.';
$lang['antivirus_maximum_recursion_invalid'] = 'Ongeldige recursie.';
$lang['antivirus_phishing_always_block_cloak'] = 'SSL cloaking scan state is invalid.';
$lang['antivirus_phishing_always_block_ssl_mismatch'] = 'Ongeldige SSL URL combinatie.';
$lang['antivirus_phishing_scan_urls_state'] = 'Ongeldige URL\'s.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Phishing signatures scan state is invalid.';
$lang['antivirus_twice_a_day'] = 'Twee keer per dag';
$lang['antivirus_update_interval'] = 'Update interval';
$lang['antivirus_updates_per_day_invalid'] = 'Ongeldig aantal updates per dag.';
