<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'Ce logiciel est fournit en plusieurs langues.  Utiliser cet outil pour régler la langue utilisée sur ce sytème.';
$lang['language_app_name'] = 'Langue';
$lang['language_default_system_language'] = 'Langue par défaut du système';
$lang['language_keyboard'] = 'Clavier';
$lang['language_keyboard_is_invalid'] = 'Le clavier est invalide.';
$lang['language_language'] = 'Langue';
$lang['language_language_is_invalid'] = 'La langue est invalide.';
$lang['language_update_my_login_session'] = 'Mise à jour de ma session de connexion';
