#!/bin/sh

# Make sure directory ownership is correct on upgrade
#----------------------------------------------------

for DIR in /var/flexshare/scripts /var/flexshare/shares; do
	CHECKPERMS=`stat --format=%a $DIR`
	if [ "$CHECKPERMS" != "755" ]; then
		logger -p local6.notice -t installer "app-flexshare-api - updating file permissions of $DIR"
		chmod 755 $DIR
	fi

	CHECKOWNERSHIP=`stat --format=%U.%G $DIR`
	if [ "$CHECKOWNERSHIP" != "root.root" ]; then
		logger -p local6.notice -t installer "app-flexshare-api - updating file ownership on $DIR"
		chown root.root $DIR
	fi
done

# Update file permissions on 4.x upgrade
#---------------------------------------

if ( [ ! -e /etc/system/initialized/flexshare ] && [ -e /etc/system/pre5x ] ); then
	find /var/flexshare/shares -type d -exec chmod u+rwx,g+rwx,o+rx '{}' \;
	find /var/flexshare/shares -type f -exec chmod u+rw,g+rw,o+r '{}' \;
	chmod 755 /var/flexshare/shares
fi

