#!/bin/sh

# Cleanup
#--------

if [ -e /var/clearos/samba/initialized ]; then
    logger -p local6.notice -t installer "app-samba-core - removing Samba initialization flag"
    rm -f /var/clearos/samba/initialized
fi

if [ -e /var/clearos/samba/domain_sid_cache ]; then
    logger -p local6.notice -t installer "app-samba-core - removing Samba SID cache"
    rm -f /var/clearos/samba/domain_sid_cache
fi

if [ -e /var/clearos/samba/domain_sid ]; then
    logger -p local6.notice -t installer "app-samba-core - removing Samba SID configuration"
    rm -f /var/clearos/samba/domain_sid
fi
