#!/usr/clearos/sandbox/usr/bin/php
<?php

/**
 * ClearOS Samba initializtion.
 *
 * @category   Apps
 * @package    Accounts
 * @subpackage Scripts
 * @author     ClearFoundation <developer@clearfoundation.com>
 * @copyright  2011 ClearFoundation
 * @license    http://www.gnu.org/copyleft/gpl.html GNU General Public License version 3 or later
 * @link       http://www.clearfoundation.com/docs/developer/apps/samba/
 */

///////////////////////////////////////////////////////////////////////////////
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

// Classes
//--------

use \clearos\apps\samba\OpenLDAP_Driver as OpenLDAP_Driver;

clearos_load_library('samba/OpenLDAP_Driver');

// Exceptions
//-----------

use \Exception as Exception;
use \clearos\apps\samba\Samba_Not_Initialized_Exception as Samba_Not_Initialized_Exception;

clearos_load_library('samba/Samba_Not_Initialized_Exception');

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

$samba = new OpenLDAP_Driver();

try {
	$samba->update_group_mappings();
} catch (Samba_Not_Initialized_Exception $e) {
	// To be expected
} catch (Exception $e) {
    clearos_log('samba', $e->GetMessage());
}
