#!/bin/sh

# Remove timesync at boot (now part of syswatch)
#-----------------------------------------------

NTPREMOVE=`grep "timesync" /etc/rc.d/rc.local 2>/dev/null`
if [ ! -z "$NTPREMOVE" ]; then
	logger -p local6.notice -t installer "app-date-core - removing old time synchronization on boot"
	grep -v 'timesync' /etc/rc.d/rc.local > /etc/rc.d/rc.local.new
	mv /etc/rc.d/rc.local.new /etc/rc.d/rc.local
	chmod 755 /etc/rc.d/rc.local
fi

# Remove old ntpdate entry
#-------------------------

OLDNTP=`grep ntpdate /etc/crontab 2>/dev/null`
if [ ! -z "$OLDNTP" ]; then
	logger -p local6.notice -t installer "app-date-core - removing old ntpdate from crontab"
	grep -v 'ntpdate' /etc/crontab > /etc/crontab.new
	mv /etc/crontab.new /etc/crontab
fi

# Remove old ntp cron job
#------------------------

if [ -e /etc/cron.d/cc-ntptime ]; then
	logger -p local6.notice -t installer "app-date-core - removing old ntpdate cron job"
	rm -f /etc/cron.d/cc-ntptime
fi

# Migrate /etc/localtime.info into /etc/sysconfig/clock
#------------------------------------------------------

if [ -e /etc/localtime.info ]; then
	THETIMEZONE=`cat /etc/localtime.info`
	CHECK=`grep ^ZONE= /etc/sysconfig/clock 2>/dev/null`

	if [ -n "$CHECK" ]; then
		logger -p local6.notice -t installer "app-date-core - migrating time zone info to /etc/sysconfig/clock"
		ESCAPEDZONE=`echo $THETIMEZONE | sed 's/\//\\\\\//'`
		sed -i -e "s/^ZONE=.*/ZONE=\"$ESCAPEDZONE\"/" /etc/sysconfig/clock
	else
		logger -p local6.notice -t installer "app-date-core - adding time zone info to /etc/sysconfig/clock"
		echo "ZONE=\"$THETIMEZONE\"/" >> /etc/sysconfig/clock
	fi

	rm -f /etc/localtime.info
fi

