#!/bin/sh

# Add sudoers entries
#--------------------

/usr/sbin/addsudo /bin/hostname app-network-core
/usr/sbin/addsudo /sbin/ethtool app-network-core
/usr/sbin/addsudo /sbin/ifdown app-network-core
/usr/sbin/addsudo /sbin/ifup app-network-core
/usr/sbin/addsudo /sbin/ip app-network-core
/usr/sbin/addsudo /sbin/iwconfig app-network-core

# Disable Avahi server
#---------------------

CHECK=`LANG=en_US /sbin/chkconfig --list avahi-daemon | /bin/grep 3:on`

if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-network-core - disabling Avahi server"
    /sbin/chkconfig avahi-daemon off
    /sbin/service avahi-daemon stop >/dev/null 2>&1
fi

# Disable PPPoE server
#---------------------

CHECK=`LANG=en_US /sbin/chkconfig --list pppoe-server | /bin/grep 3:on`

if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-network-core - disabling PPPoE server"
    /sbin/chkconfig pppoe-server off
    /sbin/service pppoe-server stop >/dev/null 2>&1
fi

