#!/bin/sh

# Disable Avahi server
#---------------------

CHECK=`LANG=en_US /sbin/chkconfig --list avahi-daemon 2>&1 | /bin/grep 3:on`

if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-network-core - disabling Avahi server"
    /sbin/chkconfig avahi-daemon off >/dev/null 2>&1
    /sbin/service avahi-daemon stop >/dev/null 2>&1
fi

# Disable PPPoE server
#---------------------

CHECK=`LANG=en_US /sbin/chkconfig --list pppoe-server | /bin/grep 3:on`

if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-network-core - disabling PPPoE server"
    /sbin/chkconfig pppoe-server off
    /sbin/service pppoe-server stop >/dev/null 2>&1
fi

