<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'L\'antivirus de la passerelle assure la protection du serveur et du réseau.';
$lang['antiphishing_app_name'] = 'Anti-hameçonnage de la passerelle';
$lang['antiphishing_app_tooltip'] = 'Tout utilisateur peut accidentellement cliquer sur un lien d\'hameçonnage.  Il est fortement recommandé de laisser activées toutes les fonctionnalités d\'anti-hameçonnage.';
$lang['antiphishing_block_cloaked'] = 'Bloquer les URLs cachées';
$lang['antiphishing_block_ssl_mismatch'] = 'Bloquer SSL discordant';
$lang['antiphishing_heuristics_engine'] = 'Moteur heuristique';
$lang['antiphishing_signature_engine'] = 'Moteur de signatures';
