#!/bin/sh

install -D -m 644 /var/webconfig/classes/lang/squid.en_US webconfig/classes/lang/squid.en_US
install -D -m 644 /var/webconfig/classes/lang/squid.es_ES webconfig/classes/lang/squid.es_ES
install -D -m 644 /var/webconfig/classes/lang/squid.fr_FR webconfig/classes/lang/squid.fr_FR
install -D -m 644 /var/webconfig/classes/lang/squid.hu_HU webconfig/classes/lang/squid.hu_HU
install -D -m 644 /var/webconfig/classes/lang/squid.it_IT webconfig/classes/lang/squid.it_IT
install -D -m 644 /var/webconfig/classes/lang/squid.nl_NL webconfig/classes/lang/squid.nl_NL
install -D -m 644 /var/webconfig/classes/lang/squid.no_NO webconfig/classes/lang/squid.no_NO
install -D -m 644 /var/webconfig/classes/lang/squid.pt_BR webconfig/classes/lang/squid.pt_BR
install -D -m 644 /var/webconfig/classes/lang/squid.da_DK webconfig/classes/lang/squid.da_DK
install -D -m 644 /var/webconfig/classes/squid.class webconfig/classes/squid.class
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.en_US webconfig/htdocs/admin/lang/squid.en_US
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.it_IT webconfig/htdocs/admin/lang/squid.it_IT
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.nl_NL webconfig/htdocs/admin/lang/squid.nl_NL
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.fr_FR webconfig/htdocs/admin/lang/squid.fr_FR
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.es_ES webconfig/htdocs/admin/lang/squid.es_ES
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.no_NO webconfig/htdocs/admin/lang/squid.no_NO
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.pt_BR webconfig/htdocs/admin/lang/squid.pt_BR
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.hu_HU webconfig/htdocs/admin/lang/squid.hu_HU
install -D -m 644 /var/webconfig/htdocs/admin/lang/squid.da_DK webconfig/htdocs/admin/lang/squid.da_DK
install -D -m 644 /var/webconfig/htdocs/admin/squid.php webconfig/htdocs/admin/squid.php
install -D -m 644 /var/webconfig/htdocs/images/icon_squid.png webconfig/htdocs/images/icon_squid.png
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.en_US webconfig/htdocs/menus/10_squid.en_US
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.es_ES webconfig/htdocs/menus/10_squid.es_ES
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.fr_FR webconfig/htdocs/menus/10_squid.fr_FR
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.hu_HU webconfig/htdocs/menus/10_squid.hu_HU
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.it_IT webconfig/htdocs/menus/10_squid.it_IT
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.nl_NL webconfig/htdocs/menus/10_squid.nl_NL
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.no_NO webconfig/htdocs/menus/10_squid.no_NO
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.pt_BR webconfig/htdocs/menus/10_squid.pt_BR
install -D -m 644 /var/webconfig/htdocs/menus/10_squid.da_DK webconfig/htdocs/menus/10_squid.da_DK
