#!/usr/bin/perl

my @files = </usr/share/squid/errors/English/*>;

foreach my $file (@files) {

	$basefile = $file;
	$basefile =~ s/.*\///;

	$errorcode = $basefile;
	$errorcode =~ s/^ERR_//;

	$targetfile = "redirect/$basefile.template";
	$url = "http://PCN_LAN_IP:82/public/proxy.php?code=$errorcode&amp;ip=%I&amp;url=%U&amp;error=%E&amp;dns=%z&amp;ftpcommand=%f&amp;ftpreply1=%F&amp;version=%s";

	print "Processing $basefile\n";

	open(TARGETFILE, ">$targetfile");
	print TARGETFILE "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN'>
<html>
	<head>
		<title>Web Proxy</title>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
		<meta http-equiv='refresh' content='0;URL=$url'>
	</head>
	<body></body>
</html>
";
	close(TARGETFILE);
}

