<!-- Base YUI -->
<script type="text/javascript" src="/templates/base/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
<script type="text/javascript" src="/templates/base/yui/build/container/container-min.js"></script>
<script type="text/javascript" src="/templates/base/yui/build/element/element-beta-min.js"></script>
<script type="text/javascript" src="/templates/base/yui/build/animation/animation-min.js"></script>
<script type="text/javascript" src="/templates/base/yui/build/connection/connection-min.js" ></script>

<!-- Global Javascript -->
<script type="text/javascript" src="/templates/base/html/base.js" ></script>

