<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'Antywirus bramy sieciowej zapewnia ochron? od strony sieci i serwera.';
$lang['antivirus_app_name'] = 'Antywirus bramy sieciowej';
$lang['antivirus_app_tooltip'] = 'Zaszyfrowane pliki s? cz?sto u?ywane do przemycania z?o?liwego oprogramowania, wi?c prosimy uwa?a? przy zezwalaniu na przepuszczenie tego typu plików przez silnik antywirusa.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Podana warto?? blokady zaszyfrowanych archiwów jest nieprawid?owa.';
$lang['antivirus_block_encrypted_files'] = 'Blokowanie zaszyfrowanych plików';
$lang['antivirus_every_two_hours'] = 'Co dwie godziny';
$lang['antivirus_maximum_file_size'] = 'Maksymalny rozmiar pliku w archiwach ZIP';
$lang['antivirus_maximum_file_size_invalid'] = 'Podany maksymalny rozmiar pliku jest nieprawid?owy.';
$lang['antivirus_maximum_files'] = 'Maksymalna liczba plików w archiwach ZIP';
$lang['antivirus_maximum_files_invalid'] = 'Podana maksymalna liczba plików jest nieprawid?owa.';
$lang['antivirus_maximum_recursion'] = 'Maksymalna warto?? rekurencji w archiwach ZIP';
$lang['antivirus_maximum_recursion_invalid'] = 'Maksymalna warto?? rekurencji jest nieprawid?owa.';
$lang['antivirus_phishing_always_block_cloak'] = 'Stan skanowania nieprawid?owo?ci SSL jest nieprawid?owy.';
$lang['antivirus_phishing_always_block_ssl_mismatch'] = 'Stan skanowania niedopasowa? URLi SSL jest nieprawid?owy.';
$lang['antivirus_phishing_scan_urls_state'] = 'Stan skanowania URLi jest nieprawid?owy.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Stan skanowania sygnatur phishingowych jest nieprawid?owy.';
$lang['antivirus_twice_a_day'] = 'Dwa razy dziennie';
$lang['antivirus_update_interval'] = 'Interwa? aktualizacji';
$lang['antivirus_updates_per_day_invalid'] = 'Podana liczba codziennych aktualizacji jest nieprawid?owa.';
