#!/usr/clearos/webconfig/usr/bin/php
<?php

/**
 * ClearOS accounts initializtion.
 *
 * @category   Apps
 * @package    Accounts
 * @subpackage Scripts
 * @author     ClearFoundation <developer@clearfoundation.com>
 * @copyright  2011 ClearFoundation
 * @license    http://www.gnu.org/copyleft/gpl.html GNU General Public License version 3 or later
 * @link       http://www.clearfoundation.com/docs/developer/apps/accounts/
 */

///////////////////////////////////////////////////////////////////////////////
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

// Classes
//--------

use \clearos\apps\ldap\LDAP_Factory as LDAP_Factory;
use \clearos\apps\mode\Mode_Engine as Mode_Engine;
use \clearos\apps\mode\Mode_Factory as Mode_Factory;
use \clearos\apps\openldap_directory\OpenLDAP as OpenLDAP;

clearos_load_library('ldap/LDAP_Factory');
clearos_load_library('mode/Mode_Engine');
clearos_load_library('mode/Mode_Factory');
clearos_load_library('openldap_directory/OpenLDAP');

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

//--------------------------------------------------------------------
// Command line options
//--------------------------------------------------------------------

$short_options  = '';
$short_options .= 'f';  // Force

$options = getopt($short_options);

$force = isset($options['f']) ? TRUE : FALSE;

//--------------------------------------------------------------------
// Initialization
//--------------------------------------------------------------------

$ldap = LDAP_Factory::create();
$sysmode = Mode_Factory::create();
$accounts_ldap = new OpenLDAP();

$mode = $sysmode->get_mode();

if ($mode === Mode_Engine::MODE_MASTER)
    $ldap->initialize_master('system.lan', NULL, $force);
else if ($mode === Mode_Engine::MODE_STANDALONE)
    $ldap->initialize_standalone('system.lan', NULL, $force);

$accounts_ldap->initialize($force);
