#!/usr/webconfig/bin/php
<?php

///////////////////////////////////////////////////////////////////////////////
//
// Copyright 2003-2006 Point Clark Networks.
//
///////////////////////////////////////////////////////////////////////////////
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
///////////////////////////////////////////////////////////////////////////////

error_reporting(0);

require_once("/var/webconfig/api/Postfix.class.php");

$postfix = new Postfix();

try {
	$domains = $postfix->GetLocalDomains();
} catch (Exception $e) {
	echo "error: " . $e->GetMessage() . "\n";
	exit(1);
}

$normal_output = "";
$amavis_output = "";

foreach ($domains as $domain) {
	$normal_output .= " $domain";
	$amavis_output .= " \".$domain\",";
}

if (isset($argv[1]) && ($argv[1] == "amavis")) {
	$amavis_output = ltrim($amavis_output);
	$amavis_output = rtrim($amavis_output, ",");
	echo "( [ $amavis_output ] )\n";
} else {
	$normal_output = ltrim($normal_output);
	echo "$normal_output\n";
}

// vim: syntax=php ts=4
?>
