#!/usr/webconfig/bin/php
<?php

///////////////////////////////////////////////////////////////////////////////
//
// Copyright 2003-2006 Point Clark Networks.
//
///////////////////////////////////////////////////////////////////////////////
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
///////////////////////////////////////////////////////////////////////////////

require_once("/var/webconfig/api/UserManager.class.php");
require_once("/var/webconfig/common/Logger.class.php");

try {
	$usermanager = new UserManager();
	$statusinfo = $usermanager->ConvertUsers();

	if (empty($statusinfo)) {
		LogIt("no users required upgrade");
	} else {
	   foreach ($statusinfo as $user => $info) {
			if ($info['status'] == UserManager::CONSTANT_EXISTS) {
				LogIt("user $user is already up-to-date");
				continue;
			}

			LogIt("user $user upgraded with the following status: " . $info['statustext']);
		}
	}
} catch (Exception $e) {
	LogIt("An error occurred: " . $e->GetMessage());
}


function LogIt($logmessage) 
{
	Logger::Syslog("upgrade-3xusers", $logmessage);
	echo "$logmessage\n";
}

// vim: syntax=php ts=4
?>
