<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'Antywirus bramy sieciowej zapewnia ochron? od strony sieci i serwera.';
$lang['antiphishing_app_name'] = 'Antiphishing bramy sieciowej';
$lang['antiphishing_app_tooltip'] = 'Nawet najbardziej ostro?ni u?ytkownicy mog? niechc?cy klikn?? w link wy?udzaj?cy informacje. Zalecamy pozostawienie w??czonych wszystkich funkcji antiphisingowych.';
$lang['antiphishing_block_cloaked'] = 'Blokowanie ukrytych URLi';
$lang['antiphishing_block_ssl_mismatch'] = 'Blokowanie niedopasowa? SSL';
$lang['antiphishing_heuristics_engine'] = 'Silnik heurystyczny';
$lang['antiphishing_signature_engine'] = 'Silnik sygnatur';
