<?php

$htmlwidth = "100%";

echo "
<div class='ui-widget' style='margin-top: 6px; margin-bottom: 6px;'>
	<div class='widget-content-header ui-state-active ui-corner-top' style='padding: 5px; width=$htmlwidth'>$title</div>
	<div class='widget-content-body ui-state-active ui-corner-bottom' style='padding: 1px; width=$htmlwidth'>
		<table cellspacing='0' cellpadding='$padding' width='100%' border='0' class='mytable' id='$id'>
";

?>
