#!/bin/sh

# FIXME - just temporary for the 6.0.0 alpha/beta - remove
if [ -d /etc/clearos/date ]; then
    rm -rf /etc/clearos/date
fi

# Enable ntpdate on boot
logger -p local6.notice -t installer "app-date-core - enabling time synchronization on boot"
chkconfig ntpdate on

# Enable hardware clock synchronization
logger -p local6.notice -t installer "app-date-core - enabling hardware time synchronization"
sed -i -e 's/SYNC_HWCLOCK=.*/SYNC_HWCLOCK=yes/' /etc/sysconfig/ntpdate

# Configure synchronization servers
logger -p local6.notice -t installer "app-date-core - configurating time synchronization servers"
install -m 0644 /usr/clearos/apps/date/deploy/step-tickers /etc/ntp/
