	<!-- Jquery Style Sheets -->
	<link type="text/css" href="/templates/amigo-5.1/css/jquery-ui/jquery-ui-1.7.2.custom.css" rel="stylesheet">
	<link type="text/css" href="/templates/amigo-5.1/css/superfish.css" rel="stylesheet">
	<link type="text/css" href="/templates/amigo-5.1/css/superfish-vertical.css" rel="stylesheet">
	<link type="text/css" href="/templates/amigo-5.1/css/superfish-navbar.css" rel="stylesheet">

	<!-- Favicon -->
	<link rel="shortcut icon" href="/templates/amigo-5.1/images/favicon.ico">

	<!-- Legacy cruft / TODO -->
	<script type="text/javascript" src="/templates/base/html/base.js"></script>

	<!-- JQuery Javascript -->
	<script type="text/javascript" src="/templates/amigo-5.1/js/jquery/jquery-1.3.2.min.js"></script>
	<script type="text/javascript" src="/templates/amigo-5.1/js/jquery-ui/jquery-ui-1.7.2.custom.min.js"></script>
	<script type="text/javascript" src="/templates/amigo-5.1/js/jquery-ui/ui.accordion.js"></script>
	<script type="text/javascript" src="/templates/amigo-5.1/js/superfish.js"></script>

<?php   $_SESSION['system_osname'] = "bob"; ?>
