<?php

///////////////////////////////////////////////////////////////////////////////
// HTML
///////////////////////////////////////////////////////////////////////////////

echo "
<!-- Body -->
<body>

<!-- Page Container -->
<div id='clearos_container'>

<div id='clearos_splash'>

<table cellspacing='0' cellpadding='0' border='0' width='500' align='center'>
	<tr>
		<td>
			<br><br>
			<p align='center'><img src='/templates/amigo-5.1/images/logo2.png' alt='ClearOS'></p>
			<br>
		</td>
	</tr>
	<tr>
		<td>
";

?>
