<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Informacje o Twojej organizacji s? u?ywane do wygenerowania certyfikatów bezpiecze?stwa i warto?ci domy?lnych do niektórych aplikacji.';
$lang['organization_app_name'] = 'Organizacja';
$lang['organization_city'] = 'Miasto';
$lang['organization_city_invalid'] = 'Podana nazwa miasta jest nieprawid?owa.';
$lang['organization_country'] = 'Kraj';
$lang['organization_country_invalid'] = 'Podana nazwa kraju jest nieprawid?owa.';
$lang['organization_organization'] = 'Organizacja';
$lang['organization_organization'] = 'Organizacja';
$lang['organization_organization_invalid'] = 'Podana nazwa organizacji jest nieprawid?owa.';
$lang['organization_postal_code'] = 'Kod pocztowy/ZIP';
$lang['organization_postal_code_invalid'] = 'Podany kod pocztowy jest nieprawid?owy.';
$lang['organization_region'] = 'Stan/Województwo';
$lang['organization_region_invalid'] = 'Podana nazwa regionu jest nieprawid?owa.';
$lang['organization_street_address'] = 'Ulica';
$lang['organization_street_address_invalid'] = 'Podana nazwa ulicy jest nieprawid?owa.';
$lang['organization_unit'] = 'Jednostka';
$lang['organization_unit_invalid'] = 'Podana nazwa jednostki jest nieprawid?owa.';
