#!/bin/sh
#
# shell script to create Bacula database(s)
#

bindir=/opt/bacula/usr/bin

if $bindir/mysql $* -f <<END-OF-DATA
CREATE DATABASE bacula;
END-OF-DATA
then
   echo "Creation of bacula database succeeded."
else
   echo "Creation of bacula database failed."
fi
exit 0
