#!/usr/bin/perl -w

###############################################################################
#
# Copyright 2002 Point Clark Networks.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
###############################################################################

use strict;
use lib '/usr/share/system/scripts';
require 'functions';

# Usual security measures... see "perlsec" manual page for details.
#------------------------------------------------------------------

$ENV {'PATH'} = '/sbin';
$ENV {'SHELL'} = '/bin/bash';
delete $ENV {'ENV', 'BASH_ENV'};

if ($< != 0) {
	print("You must be root to update system files... exiting.\n");
	exit;
}

my $f_resolv = "/etc/resolv.conf";
my $f_temp = "/tmp/app-resolv.conf";

# Main
#-----

open(TEMP, ">$f_temp") or die "File open error $f_temp: $!";
foreach my $arg (@ARGV) {
	print TEMP "nameserver $arg\n";
}
close (TEMP);
system("/bin/mv $f_temp $f_resolv");

