<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = '网关反钓鱼保护你的网络和服务器，阻挡钓鱼链接。';
$lang['antiphishing_app_name'] = '网关反钓鱼';
$lang['antiphishing_app_tooltip'] = '即使最精明的用户也可能不经意间点击钓鱼链接。所以请尽量使能反钓鱼功能。';
$lang['antiphishing_block_cloaked'] = '阻拦隐形URL';
$lang['antiphishing_block_ssl_mismatch'] = '阻拦SSL 不匹配';
$lang['antiphishing_heuristics_engine'] = '启发式引擎';
$lang['antiphishing_signature_engine'] = '签名引擎';
