#!/bin/sh

TEMP_PATH="/var/tmp"

# CLEAROS_DEVEL_BASENAME=`basename "$0"`

# FIXME: change "modules" to "apps"
# CLEAROS_APP_PATH=`readlink -f "$0" | sed "s/tools\/$CLEAROS_DEVEL_BASENAME/modules/"`
# CLEAROS_BASE_PATH=`readlink -f "$0" | sed "s/\/tools\/$CLEAROS_DEVEL_BASENAME//"`
# export CLEAROS_APP_PATH
# export CLEAROS_BASE_PATH

WEBCONFIG_UID=`id -u`
WEBCONFIG_PORT="1`id -u`"
WEBCONFIG_BIN="$TEMP_PATH/webconfig-$USER-bin"
WEBCONFIG_HTTPD_CONF="/var/tmp/webconfig-$USER.conf"
WEBCONFIG_HTTPD_TEMPLATE="`dirname $PWD/$0`/webconfig-devel.conf.template"

# FIXME: remove trunk
WEBCONFIG_ROOT_ESCAPED=`dirname $PWD/$0 | sed 's/\/tools\/trunk//' | sed 's/\//\\\\\//g'`

if [ "$WEBCONFIG_UID" == "0" ]; then
	echo "Development with root account is not supported.  Please use a regular user account."
	exit 1
fi

# Create a link to webconfig so that we have a different process name
if [ ! -e $WEBCONFIG_BIN ]; then
	ln -s /usr/sbin/webconfig $WEBCONFIG_BIN
fi

# Generate our Apache configuration using the template
sed -e "s/WEBCONFIG_ROOT/$WEBCONFIG_ROOT_ESCAPED/" "$WEBCONFIG_HTTPD_TEMPLATE" | \
sed -e "s/WEBCONFIG_PORT/$WEBCONFIG_PORT/" | \
sed -e "s/WEBCONFIG_USER/$USER/" \
> "$WEBCONFIG_HTTPD_CONF"

# Startup webconfig in developer mode
echo "root password is required to start the development mode webconfig"
su -c "killall $WEBCONFIG_BIN; sleep 1; $WEBCONFIG_BIN -f $WEBCONFIG_HTTPD_CONF"

echo "Started webconfig on port $WEBCONFIG_PORT"
