<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'Gateway Antivirüsü aðýnýzda dolaþabilecek virüslere karþý sunucunuzu korur.';
$lang['antiphishing_app_name'] = 'Gateway Antiphishing (Sahte Kimlik Avý)';
$lang['antiphishing_app_tooltip'] = 'En iyi internet kullanýcýsý bile yanlýþlýkla sahte bir linkte týklayabilir ve kimlik avý dolandýrýcýlýðýna maruz kalabilir, bu yüzden tüm güvenlik seçeneklerini aktif etmenizi tavsiye ederiz.';
$lang['antiphishing_block_cloaked'] = 'Gizli URL\'leri Engelle';
$lang['antiphishing_block_ssl_mismatch'] = 'Uyumsuz SSL\'leri Engelle';
$lang['antiphishing_heuristics_engine'] = 'Sezgisel Tarama Motoru';
$lang['antiphishing_signature_engine'] = 'Ýmza Tarama Motoru';
