<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'La porta d\'enllaç de l\'Antivirus proporciona protecció per la seva xarxa i servidor.';
$lang['antivirus_app_name'] = 'Porta d\'entrada de l\'Antivirus';
$lang['antivirus_app_tooltip'] = 'Els arxius xifrats sovint s\'usen per mostrar el malware, així que si us plau vagi amb compte amb el que permeten aquest tipus d\'arxius a través del motor de l\'antivirus';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'El valor de bloqueig d\'arxius encriptats no és vàlid';
$lang['antivirus_block_encrypted_files'] = 'Bloquejar arxius xifrats';
$lang['antivirus_every_two_hours'] = 'Cada dues hores';
$lang['antivirus_maximum_file_size'] = 'Mida màxima d\'arxius Zip';
$lang['antivirus_maximum_file_size_invalid'] = 'El valor maxim del fitxer no es vàlid';
$lang['antivirus_maximum_files'] = 'Màxim de fitxers en arxius ZIP';
$lang['antivirus_maximum_files_invalid'] = 'La capacitat màxima de fitxers no és vàlida';
$lang['antivirus_maximum_recursion'] = 'Maxim de recursivitat d\'arxius Zip';
$lang['antivirus_maximum_recursion_invalid'] = 'Maximum recursion is invalid.';
$lang['antivirus_phishing_always_block_cloak'] = 'SSL cloaking scan state is invalid.';
$lang['antivirus_phishing_always_block_ssl_mismatch'] = 'SSL no coincideix amb URL l\'estat d\'exploració no és vàlid';
$lang['antivirus_phishing_scan_urls_state'] = 'L\'escaneig de direccions URLs no es vàlid';
$lang['antivirus_phishing_signatures_state_invalid'] = 'L\'escaneig de signatures Phising no es vàlid';
$lang['antivirus_twice_a_day'] = 'Dues vegades al dia';
$lang['antivirus_update_interval'] = 'Interval d\'actualització';
$lang['antivirus_updates_per_day_invalid'] = 'El nombre d\'actualitzacions per dia es invàlid';
