<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'Aquest software es proporciona amb molts llenguatges.  Utilitza aquesta eina per configurar el llenguatge del sistema per defecte. ';
$lang['language_app_name'] = 'Llenguatge';
$lang['language_default_system_language'] = 'Llenguatge per defecte del sistema';
$lang['language_keyboard'] = 'Teclat';
$lang['language_keyboard_is_invalid'] = 'El teclat és invàlid';
$lang['language_language'] = 'Llengua';
$lang['language_language_is_invalid'] = 'La llengua és incorrecta';
$lang['language_update_my_login_session'] = 'Actualitza la meva Sessió';
