<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Narz?dzie do zmiany strefy czasowej i synchronizacji czasu.';
$lang['date_app_name'] = 'Date and Time';
$lang['date_app_tooltip'] = 'VoIP, us?ugi uwierzytelniania oraz inne aplikacje wymagaj? poprawnego ustawienia czasu, wi?c prosimy upewni? si?, ?e zegar i strefa czasowa s? prawid?owe!';
$lang['date_date'] = 'Data';
$lang['date_synchronization_changed_time_by_x_seconds:'] = 'Proces synchronizacji zmieni? czas systemowy o nast?puj?c? liczb? sekund:';
$lang['date_synchronize_now'] = 'Synchronizuj';
$lang['date_time'] = 'Czas';
$lang['date_time_server'] = 'Serwer czasu';
$lang['date_time_server_is_invalid'] = 'Podana nazwa serwera czasu jest nieprawid?owa.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Harmonogram synchronizacji czasu jest nieprawid?owy.';
$lang['date_time_zone'] = 'Strefa czasowa';
$lang['date_time_zone_is_invalid'] = 'Podana nazwa strefy czasowej jest nieprawid?owa.';
