<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Outil de synchronisation de l\'horloge et du fuseau horaire.';
$lang['date_app_name'] = 'Heure et date';
$lang['date_app_tooltip'] = 'La VoIP, les services d\'authentification et d\'autres applications nécessitent des réglages appropriés de l\'heure, aussi veuillez vérifier que l\'heure et le fuseau horaire sont corrects!';
$lang['date_date'] = 'Date';
$lang['date_synchronization_changed_time_by_x_seconds:'] = 'La synchronisation a modifié l\'heure système du nombre de secondes suivant:';
$lang['date_synchronize_now'] = 'Synchroniser maintenant';
$lang['date_time'] = 'Heure';
$lang['date_time_server'] = 'Serveur de temps';
$lang['date_time_server_is_invalid'] = 'Le serveur de temps n\'est pas valide.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'La planification de la synchronisation n\'est pas valide.';
$lang['date_time_zone'] = 'Fuseau horaire';
$lang['date_time_zone_is_invalid'] = 'Le fuseau horaire n\'est pas valide.';
