<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_summary'] = 'Time and Date';
$lang['date_app_long_description'] = 'The time zone and clock synchronization tool.';
$lang['date_app_tooltip'] = 'VoIP, authentication services and other applications require proper time settings, so please make sure your clock and time zone are correct!';
$lang['date_date'] = 'La Date';
$lang['date_synchronize_now'] = 'Synchronize Now';
$lang['date_time'] = 'Time';
$lang['date_time_and_date'] = 'Time and Date';
$lang['date_date_and_time'] = 'La Date et Lheure';
$lang['date_time_server'] = 'Time Server';
$lang['date_time_server_is_invalid'] = 'Time server is invalid.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Time synchronization schedule is invalid.';
$lang['date_time_zone'] = 'Time Zone';
$lang['date_time_zone_is_invalid'] = 'Time zone is invalid.';
