<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'L\'information concernant votre organisation est utilisée pour générer les certificats de sécurité et pour régler certaines valeurs par défaut.';
$lang['organization_app_name'] = 'Oraganisation';
$lang['organization_city'] = 'Ville';
$lang['organization_city_invalid'] = 'La ville est invalide.';
$lang['organization_country'] = 'Pays';
$lang['organization_country_invalid'] = 'Le pays est invalide.';
$lang['organization_organization'] = 'Organisation';
$lang['organization_organization'] = 'Organisation';
$lang['organization_organization_invalid'] = 'L\'organisation est invalide.';
$lang['organization_postal_code'] = 'Code postal';
$lang['organization_postal_code_invalid'] = 'Le code postal est invalide.';
$lang['organization_region'] = 'Département';
$lang['organization_region_invalid'] = 'La région est invalide.';
$lang['organization_street_address'] = 'Adresse';
$lang['organization_street_address_invalid'] = 'L\'adresse est invalide.';
$lang['organization_unit'] = 'Service';
$lang['organization_unit_invalid'] = 'Le service est invalide.';
