<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antiphishing_app_description'] = 'Perlindungan antivirus untuk Gateway melindungi jaringan ( Lan ) dan server anda.';
$lang['antiphishing_app_name'] = 'Antiphishing Gateway';
$lang['antiphishing_app_tooltip'] = 'Bahkan untuk user tingkat lanjutpun bisa terjebak dalam link phishing. Jadi kami merekomendasikan semua fitur antiphishing di enable kan.';
$lang['antiphishing_block_cloaked'] = 'blok URL yang tak di kenal';
$lang['antiphishing_block_ssl_mismatch'] = 'Blok SSL yang tidak cocok';
$lang['antiphishing_heuristics_engine'] = 'Mesin heuristik';
$lang['antiphishing_signature_engine'] = 'Tanda tangan mesin';
