#!/bin/sh

# ip-up.local changes
#--------------------

CHECK=`grep '/etc/rc.d/init.d/firewall' /etc/ppp/ip-up.local 2>/dev/null`
if [ -n "$CHECK" ]; then
	logger -p local6.notice -t installer "app-ppp - removing old PPP firewall extras"
	grep -v '/etc/rc.d/init.d/firewall' /etc/ppp/ip-up.local > /etc/ppp/ip-up.local.new
	mv /etc/ppp/ip-up.local.new /etc/ppp/ip-up.local
	chmod 755 /etc/ppp/ip-up.local
fi

CHECK=`grep '/usr/local/system/scripts/firewall-up' /etc/ppp/ip-up.local 2>/dev/null`
if [ -n "$CHECK" ]; then
	logger -p local6.notice -t installer "app-ppp - removing old PPP firewall extras script"
	grep -v '/usr/local/system/scripts/firewall-up' /etc/ppp/ip-up.local > /etc/ppp/ip-up.local.new
	mv /etc/ppp/ip-up.local.new /etc/ppp/ip-up.local
	chmod 755 /etc/ppp/ip-up.local
fi

CHECK=`grep '/usr/share/system/scripts/firewall-up' /etc/ppp/ip-up.local 2>/dev/null`
if [ -z "$CHECK" ]; then
	logger -p local6.notice -t installer "app-ppp - adding PPTP and multiwan support"
	echo "/usr/share/system/scripts/firewall-up \$1" >> /etc/ppp/ip-up.local
	cp /etc/ppp/ip-up.local /usr/share/system/modules/ppp/ip-up.local
	chmod 755 /etc/ppp/ip-up.local
fi

# Configuration file changes
#---------------------------

if [ -e /etc/ppp/pppoe.conf ]; then
	if [ -e /etc/sysconfig/network-scripts/ifcfg-ppp0 ]; then
		logger -p local6.notice -t installer "app-ppp - unable to convert old pppoe.conf file"
	else
		logger -p local6.notice -t installer "app-ppp - converting old pppoe.conf file"
		cp /etc/ppp/pppoe.conf /etc/sysconfig/network-scripts/ifcfg-ppp0
		mv /etc/ppp/pppoe.conf /etc/ppp/pppoe.conf-moved-to-etc_sysconfig_network-scripts_ifcfg-ppp0
		grep -v "^#" /etc/sysconfig/network-scripts/ifcfg-ppp0 > /tmp/ifcfg.ppp0.new
		mv /tmp/ifcfg.ppp0.new /etc/sysconfig/network-scripts/ifcfg-ppp0
		grep -v "^[[:space:]]*$" /etc/sysconfig/network-scripts/ifcfg-ppp0 > /tmp/ifcfg.ppp0.new
		mv /tmp/ifcfg.ppp0.new /etc/sysconfig/network-scripts/ifcfg-ppp0
		sed -e 's/TYPE=.*/TYPE=xDSL/' /etc/sysconfig/network-scripts/ifcfg-ppp0 > /tmp/ifcfg.ppp0.new
		mv /tmp/ifcfg.ppp0.new /etc/sysconfig/network-scripts/ifcfg-ppp0
	fi
fi

if [ -e /etc/sysconfig/network-scripts/ifcfg-ppp0 ]; then
	. /etc/sysconfig/network-scripts/ifcfg-ppp0
	if [ "$TYPE" != "xDSL" ]; then
		logger -p local6.notice -t installer "app-ppp - converting old xDSL type in configuration"
		sed -e 's/TYPE=.*/TYPE=xDSL/' /etc/sysconfig/network-scripts/ifcfg-ppp0 > /tmp/ifcfg.ppp0.new
		mv /tmp/ifcfg.ppp0.new /etc/sysconfig/network-scripts/ifcfg-ppp0
	fi
fi
