#!/usr/webconfig/bin/php
<?php

///////////////////////////////////////////////////////////////////////////////
//
// Copyright 2009 Point Clark Networks.
//
///////////////////////////////////////////////////////////////////////////////
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
///////////////////////////////////////////////////////////////////////////////

$BASEDIR = isset($_ENV['WEBCONFIG_ROOT']) ? $_ENV['WEBCONFIG_ROOT'] : "/var/webconfig";

require_once($BASEDIR . '/api/DansGuardianAv.class.php');
require_once($BASEDIR . '/api/Firewall.class.php');
require_once($BASEDIR . '/api/Iface.class.php');

$firewall = new Firewall();

try {
    $fwmode = $firewall->GetMode();
    $laninterface = $firewall->GetInterfaceDefinition(Firewall::CONSTANT_LAN);
    $extinterface = $firewall->GetInterfaceDefinition(Firewall::CONSTANT_EXTERNAL);
} catch (Exception $e) {
	echo "error: " . $e->getMessage() . "\n";
	exit(1);
}

// Determine which network interface to use
//-----------------------------------------

if ($extinterface && (($fwmode == Firewall::CONSTANT_STANDALONE) || ($fwmode == Firewall::CONSTANT_TRUSTEDSTANDALONE)))
	$useinterface = $extinterface;
else if ($laninterface)
	$useinterface = $laninterface;
else
	exit(0);

// Determine the IP address to use in access denied URL
//-----------------------------------------------------

try {
    $iface = new Iface($useinterface);

    if ($iface->IsConfigured())
		$ip = $iface->GetLiveIp();

	if (empty($ip))
		exit(0);
} catch (Exception $e) {
	echo "error: " . $e->getMessage() . "\n";
	exit(1);
}

// Set the access denied URL
//--------------------------

try {
	$dansguardian = new DansGuardian();
    $ourconfig = $dansguardian->GetAccessDeniedUrl();

    if ($ip && (preg_match("/\/filtered.php/", $ourconfig) || preg_match("/YOURSERVER/", $ourconfig)))
        $dansguardian->SetAccessDeniedUrl("http://$ip:82/public/filtered.php");

} catch (Exception $e) {
	echo "error: " . $e->getMessage() . "\n";
	exit(1);
}

// vim: syntax=php ts=4
?>
