<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Tidszon och synkronisering av klockan.';
$lang['date_app_name'] = 'Datum och tid';
$lang['date_app_tooltip'] = 'VOIP, autentisieringstjänster och andra applikationer kräver noggranna tidsangivelser, var därför noggrann med att din klocka och tidszon är korrekta!';
$lang['date_date'] = 'Datum';
$lang['date_synchronization_changed_time_by_x_seconds:'] = 'Synkroniseringen ändrade systemtiden med följande antal sekunder:';
$lang['date_synchronize_now'] = 'Synkronisera nu';
$lang['date_time'] = 'Klockslag';
$lang['date_time_server'] = 'Tidsserver';
$lang['date_time_server_is_invalid'] = 'Tidsservern är ogiltig.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Schemat för tidssynkronisering är ogiltigt.';
$lang['date_time_zone'] = 'Tidszon';
$lang['date_time_zone_is_invalid'] = 'Tidszonen är ogiltig.';
