<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'Denna programvara finns för många olika språk.  Använd detta verktyg för att ställa in det förvalda språket för ditt system.';
$lang['language_app_name'] = 'Språk';
$lang['language_default_system_language'] = 'Förvalt språk för systemet';
$lang['language_keyboard'] = 'Tangentbord';
$lang['language_keyboard_is_invalid'] = 'Ogiltigt tangentbord.';
$lang['language_language'] = 'Språk';
$lang['language_language_is_invalid'] = 'Ogiltigt språk.';
$lang['language_update_my_login_session'] = 'Uppdatera min inloggningssession';
