#!/bin/sh

# Add daemon setting
#------------------------------------------------------------------

CHECK=`grep ^user /etc/dnsmasq.conf 2>/dev/null`
if [ -z "$CHECK" ]; then
	logger -p local6.notice -t installer "app-dns - adding daemon user setting to configuration"
	echo "user=nobody" >> /etc/dnsmasq.conf
fi
