<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = '本软件提供多种语言支持，这里可以设置系统默认语言。';
$lang['language_app_name'] = '语言';
$lang['language_default_system_language'] = '系统默认语言';
$lang['language_keyboard'] = '键盘';
$lang['language_keyboard_is_invalid'] = '键盘布局无效';
$lang['language_language'] = '语言';
$lang['language_language_is_invalid'] = '语言无效';
$lang['language_update_my_login_session'] = '更新登陆会话';
