<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'This software is provided in many different languages.  Use this tool to set the default language for the system.';
$lang['language_app_name'] = '语言';
$lang['language_default_system_language'] = 'Default System Language';
$lang['language_keyboard'] = '键盘';
$lang['language_keyboard_is_invalid'] = 'Keyboard is invalid.';
$lang['language_language'] = '语言';
$lang['language_language_is_invalid'] = 'Language is invalid.';
$lang['language_update_my_login_session'] = 'Update My Login Session';
