#!/bin/sh

# FIXME: slapd.d keeps re-appearing
if [ -d /etc/openldap/slapd.d ]; then
	rm /etc/openldap/slapd.d -rf
fi

# Initialize LDAP
[ -x /usr/sbin/ldap-synchronize ] && /usr/sbin/ldap-synchronize >/dev/null 2>&1
[ -x /usr/sbin/ldap-init ] && /usr/sbin/ldap-init >/dev/null 2>&1

# FIXME: Initialize Accounts - alpha only
[ -x /usr/sbin/accounts-init ] && /usr/sbin/accounts-init >/dev/null 2>&1
