<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Informació sobre la seva organització s\'utilitza per generar certificats de seguretat i altres valors predeterminats del programari.';
$lang['organization_app_name'] = 'Organització';
$lang['organization_city'] = 'Ciutat';
$lang['organization_city_invalid'] = 'La ciutat no és vàlida ';
$lang['organization_country'] = 'Pais';
$lang['organization_country_invalid'] = 'Pais no vàlid';
$lang['organization_organization'] = 'Organització';
$lang['organization_organization'] = 'Organization';
$lang['organization_organization_invalid'] = 'organització no valida';
$lang['organization_postal_code'] = 'Codi postal';
$lang['organization_postal_code_invalid'] = 'Codi postal no vàlid';
$lang['organization_region'] = 'Estat/Província';
$lang['organization_region_invalid'] = 'Regió no vàlida';
$lang['organization_street_address'] = 'Direcció';
$lang['organization_street_address_invalid'] = 'La direcció del carrer no es vàlida';
$lang['organization_unit'] = 'Unitat';
$lang['organization_unit_invalid'] = 'Unitat no valida';
