<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Kuruluþunuz hakkýnda bilgiler, güvenlik sertifikalarý ve diðer yazýlým varsayýlanlarý oluþturmak için aþaðýdaki alanlarý doldurun.';
$lang['organization_app_name'] = 'Kuruluþ/Firma';
$lang['organization_city'] = 'Þehir';
$lang['organization_city_invalid'] = 'Þehir adý geçerli deðil.';
$lang['organization_country'] = 'Ülke';
$lang['organization_country_invalid'] = 'Ülke adý geçerli deðil.';
$lang['organization_organization'] = 'Kuruluþ/Firma';
$lang['organization_organization'] = 'Kuruluþ/Firma';
$lang['organization_organization_invalid'] = 'Kuruluþ/Firma adý geçerli deðil.';
$lang['organization_postal_code'] = 'Posta/Zip Kodu';
$lang['organization_postal_code_invalid'] = 'Posta kodu geçerli deðil.';
$lang['organization_region'] = 'Devlet/Þehir';
$lang['organization_region_invalid'] = 'Bölge adý geçerli deðil.';
$lang['organization_street_address'] = 'Cadde-Sokak adresi';
$lang['organization_street_address_invalid'] = 'Cadde-Sokak adresi geçerli deðil';
$lang['organization_unit'] = 'Departman';
$lang['organization_unit_invalid'] = 'Departman adý geçerli deðil.';
