<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Информация о вашей организации используется для генерации сертификата и других программ по умолчанию';
$lang['organization_app_name'] = 'Организация';
$lang['organization_city'] = 'Город';
$lang['organization_city_invalid'] = 'Город неверен';
$lang['organization_country'] = 'Страна';
$lang['organization_country_invalid'] = 'Страна неверна';
$lang['organization_organization'] = 'Organization';
$lang['organization_organization'] = 'Организация';
$lang['organization_organization_invalid'] = 'Организация неверна';
$lang['organization_postal_code'] = 'Индекс';
$lang['organization_postal_code_invalid'] = 'Индекс неверный';
$lang['organization_region'] = 'Область';
$lang['organization_region_invalid'] = 'Регион неверный';
$lang['organization_street_address'] = 'Улица';
$lang['organization_street_address_invalid'] = 'Улица неверна';
$lang['organization_unit'] = 'Unit';
$lang['organization_unit_invalid'] = 'Unit is invalid.';
