<?php
// Generated by export.php.
$lang['antivirus_avd_flexshare'] = 'Flexshares';
$lang['antivirus_avd_ftp'] = 'FTP Files';
$lang['antivirus_avd_home'] = 'Home Directories';
$lang['antivirus_avd_imap'] = 'Mailboxes';
$lang['antivirus_avd_shared'] = 'Shared Files';
$lang['antivirus_avd_squid'] = 'Web Proxy Cache';
$lang['antivirus_avd_www'] = 'Website Files';
$lang['antivirus_config_error'] = 'Error accessing configuration.';
$lang['antivirus_dir_exists'] = 'Directory already added.';
$lang['antivirus_dir_not_found'] = 'Directory not found.';
$lang['antivirus_file_not_found'] = 'File not found.';
$lang['antivirus_not_running'] = 'Scanner is not running.';
$lang['antivirus_running'] = 'Scanner is already running.';
$lang['antivirus_state_error'] = 'Error accessing scanner state file.';
// vi: syntax=php ts=4

$lang['file_scan_antimalware'] = 'Antimalware';
$lang['file_scan_antimalware_file_scanner'] = 'Antimalware File Scanner';
$lang['file_scan_daily_scan'] = 'Daily Scan';
$lang['file_scan_directories'] = 'Directories';
$lang['file_scan_home'] = 'Home';
$lang['file_scan_web'] = 'Web';
$lang['file_scan_ftp'] = 'FTP';
$lang['file_scan_flexshare'] = 'Flexshare';
$lang['file_scan_web_proxy_cache'] = 'Web Proxy Cache';
$lang['file_scan_last_run'] = 'Last Run';
$lang['file_scan_errors'] = 'Errors';
$lang['file_scan_malware_items_found'] = 'Malware Items Found';
$lang['file_scan_last_scan_result'] = 'Last Scan Result';
$lang['file_scan_progress'] = 'Progress';
$lang['file_scan_malware_found'] = 'Malware found!';
$lang['file_scan_no_malware_found'] = 'No malware found.';
$lang['file_scan_idle'] = 'Idle';
$lang['file_scan_interrupted'] = 'Interrupted';
$lang['file_scan_scanning'] = 'Scanning';
$lang['file_scan_scanner'] = 'Scanner';
$lang['file_scan_last_run'] = 'Last scanner run: %s';
$lang['file_scan_currently_scanning'] = 'Currently scanning %s';
$lang['file_scan_malware'] = 'Malware';
$lang['file_scan_file'] = 'File';

?>
