<?php
// Generated by export.php.
$lang['antivirus_avd_flexshare'] = 'Flexshares';
$lang['antivirus_avd_ftp'] = 'FTP Files';
$lang['antivirus_avd_home'] = 'Home Directories';
$lang['antivirus_avd_imap'] = 'Mailboxes';
$lang['antivirus_avd_shared'] = 'Shared Files';
$lang['antivirus_avd_squid'] = 'Web Proxy Cache';
$lang['antivirus_avd_www'] = 'Website Files';
$lang['antivirus_config_error'] = 'Error accessing configuration.';
$lang['antivirus_dir_exists'] = 'Directory already added.';
$lang['antivirus_dir_not_found'] = 'Directory not found.';
$lang['antivirus_file_not_found'] = 'File not found.';
$lang['antivirus_not_running'] = 'Scanner is not running.';
$lang['antivirus_running'] = 'Scanner is already running.';
$lang['antivirus_state_error'] = 'Error accessing scanner state file.';
// vi: syntax=php ts=4

$lang['filescan_antimalware'] = 'Antimalware File Scanner';
$lang['filescan_daily_scan'] = 'Daily Scan';
$lang['filescan_directories'] = 'Directories';
$lang['filescan_home'] = 'Home';
$lang['filescan_web'] = 'Web';
$lang['filescan_ftp'] = 'FTP';
$lang['filescan_flexshare'] = 'Flexshare';
$lang['filescan_web_proxy_cache'] = 'Web Proxy Cache';
$lang['filescan_last_run'] = 'Last Run';
$lang['filescan_errors'] = 'Errors';
$lang['filescan_malware_items_found'] = 'Malware Items Found';
$lang['filescan_last_scan_result'] = 'Last Scan Result';
$lang['filescan_progress'] = 'Progress';

?>
