#!/usr/webconfig/bin/php
<?php

///////////////////////////////////////////////////////////////////////////////
//
// Copyright 2006 Point Clark Networks.
//
///////////////////////////////////////////////////////////////////////////////
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
///////////////////////////////////////////////////////////////////////////////

require_once("/var/webconfig/api/Cyrus.class.php");

$rawprotocols = isset($argv[1]) ? trim($argv[1]) : "";

try {
	$cyrus = new Cyrus();
	$validprotocols = $cyrus->GetServiceList();

	$protocols = preg_split("/\s+/", $rawprotocols);

	foreach ($validprotocols as $protocol)
		$cyrus->DisableService($protocol);

	foreach ($protocols as $protocol) {
		if (in_array($protocol, $validprotocols)) {
			LogIt("enabling mail service: $protocol");
			$cyrus->EnableService($protocol);
		}
	}

} catch (Exception $e) {
	LogIt("An error occurred: " . $e->GetMessage());
}

function LogIt($logmessage) 
{
	Logger::Syslog("cyrusadmin", $logmessage);
	echo "$logmessage\n";
}

// vim: syntax=php ts=4
?>
