<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'This software is provided in many different languages.  Use this tool to set the default language for the system.';
$lang['language_app_name'] = 'Language';
$lang['language_keyboard'] = 'Keyboard';
$lang['language_keyboard_is_invalid'] = 'Keyboard is invalid.';
$lang['language_language'] = 'La Langue';
$lang['language_language_is_invalid'] = 'Language is invalid.';
