#!/usr/webconfig/bin/php -q
<?php

///////////////////////////////////////////////////////////////////////////////
//
// Copyright 2006 Point Clark Networks.
//
///////////////////////////////////////////////////////////////////////////////
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
///////////////////////////////////////////////////////////////////////////////

require_once("/var/webconfig/api/DansGuardian.class.php");

$dansguardian = new DansGuardian();

try {
	$cleanedblacklist = $dansguardian->CleanBlacklists();
	$cleanedphraselist = $dansguardian->CleanWeightedPhraselists();
} catch (Exception $e) {
	LogIt("an error occurred: " . $e->GetMessage());
}

foreach ($cleanedblacklist as $list)
	LogIt("Removed non-existant blacklist: $list");

foreach ($cleanedphraselist as $list)
	LogIt("Removed non-existant weighted phrase list: $list");

function LogIt($logmessage)
{
	Logger::Syslog("dansguardian", $logmessage);
	echo "$logmessage\n";
}

// vim: syntax=php ts=4
?>
