#!/usr/webconfig/bin/php
<?php

///////////////////////////////////////////////////////////////////////////////
//
// Copyright 2009 Point Clark Networks.
//
///////////////////////////////////////////////////////////////////////////////
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
///////////////////////////////////////////////////////////////////////////////

$BASEDIR = isset($_ENV['WEBCONFIG_ROOT']) ? $_ENV['WEBCONFIG_ROOT'] : "/var/webconfig";

require_once($BASEDIR . "/common/Logger.class.php");
require_once($BASEDIR . "/api/ClearDirectory.class.php");
require_once($BASEDIR . "/api/Organization.class.php");
require_once($BASEDIR . "/api/Samba.class.php");

// Initialize LDAP
//----------------

try {
	$organization = new Organization();
	$domain = $organization->GetDomain();

	if (!empty($domain)) {
		$directory = new ClearDirectory();
		$initialized = $directory->IsInitialized();

		if (!$initialized)
			$directory->Initialize(ClearDirectory::CONSTANT_ROLE_MASTER, $domain);
	}
} catch (Exception $e) {
    LogIt($e->GetMessage());
}

// Initialize Samba elements in LDAP
//----------------------------------

try {
	$samba = new Samba();

	if (!$samba->IsDirectoryInitialized()) {
		$workgroup = $samba->GetWorkgroup();
		$samba->InitializeDirectory($workgroup);
	}
} catch (Exception $e) {
    LogIt($e->GetMessage());
}

// Log routine
//------------

function LogIt($logmessage)
{
	Logger::Syslog("usersetup", $logmessage);
	echo "$logmessage\n";
}

// vim: syntax=php ts=4
?>
