#!/usr/webconfig/bin/php
<?php

///////////////////////////////////////////////////////////////////////////////
//
// Copyright 2009 Point Clark Networks.
//
///////////////////////////////////////////////////////////////////////////////
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
///////////////////////////////////////////////////////////////////////////////

$BASEDIR = isset($_ENV['WEBCONFIG_ROOT']) ? $_ENV['WEBCONFIG_ROOT'] : "/var/webconfig";

require_once($BASEDIR . "/api/File.class.php");
require_once($BASEDIR . "/api/ShellExec.class.php");
require_once($BASEDIR . "/api/SoftwareUpdate.class.php");

// Bail if system is busy
//-----------------------

$update = new SoftwareUpdate();

try {
	if ($update->IsBusy())
		throw new SoftwareUpdateBusyException();
} catch (Exception $e) {
	echo "warning: " . $e->GetMessage() . "\n";
}

// Open log file right away
//-------------------------

$file = new File(COMMON_TEMP_DIR . "/" . SoftwareUpdate::FILE_INSTALL_LOG);

try {
	if (! $file->Exists())
		$file->Create("webconfig", "webconfig", "0644");

	$file->AddLines(SOFTWAREUPDATE_LANG_INSTALLING . "...\n");
} catch (Exception $e) {
	echo "error: " . $e->GetMessage() . "\n";
}

// Create RPM list
//----------------

array_shift($argv);
$rpmlist = "";

foreach ($argv as $rpm)
	$rpmlist .= $rpm . " ";

// Run install
//------------

try {
	$options = array();
	$options['log'] = SoftwareUpdate::FILE_INSTALL_LOG;
	$options['env'] = SoftwareUpdate::ENV_GNUPG;

	$shell = new ShellExec();
	$shell->Execute(SoftwareUpdate::COMMAND_YUM, "-y install $rpmlist", true, $options);

	// Push log information into /var/log/system
	//------------------------------------------

	$file = new File(COMMON_TEMP_DIR . "/" . SoftwareUpdate::FILE_INSTALL_LOG);
	$lines = $file->GetContentsAsArray();

	Logger::Syslog("software-update", "log: ------------------- software update ------------------------------");

	foreach ($lines as $line)
		Logger::Syslog("installer", "log: $line", "local6");

	Logger::Syslog("software-update", "log: ------------------- software update complete ---------------------");
} catch (Exception $e) {
	echo "error: " . $e->GetMessage() . "\n";
}

?>
