#!/bin/sh

bindir=/opt/bacula/usr/bin

if [ $# -ne 3 ]; then
    echo "Wrong number of args, expected 3."
    exit 1
fi

# $1 HOST
# $2 PORT
# $3 PASS

$bindir/mysql mysql -h$1 -P$2 -uroot \
	-e "UPDATE user SET password = PASSWORD('$3') WHERE User = 'bacula';"
$bindir/mysqladmin -h$1 -P$2 -uroot reload

exit $?
