<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = '反病毒网关保护你的网络和服务器。';
$lang['antivirus_app_name'] = '网关反病毒';
$lang['antivirus_app_tooltip'] = '加密的文件常用来传输恶意软件，请慎重允许这些类型的软件通过反病毒引擎。';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = '阻拦加密存档无效';
$lang['antivirus_block_encrypted_files'] = '阻拦加密文件';
$lang['antivirus_every_two_hours'] = '每两小时';
$lang['antivirus_maximum_file_size'] = '最大Zip文件';
$lang['antivirus_maximum_file_size_invalid'] = '文件最大个头无效。';
$lang['antivirus_maximum_files'] = 'Zip文件中最大文件数';
$lang['antivirus_maximum_files_invalid'] = '文件最大数无效。';
$lang['antivirus_maximum_recursion'] = 'Zip文件最大递归';
$lang['antivirus_maximum_recursion_invalid'] = '最大递归无效';
$lang['antivirus_phishing_always_block_cloak'] = 'SSL隐形扫描状态无效';
$lang['antivirus_phishing_always_block_ssl_mismatch'] = 'SSL URL匹配扫描状态无效。';
$lang['antivirus_phishing_scan_urls_state'] = 'URL扫描状态无效。';
$lang['antivirus_phishing_signatures_state_invalid'] = '网络钓鱼扫描状态无效。';
$lang['antivirus_twice_a_day'] = '每天两次';
$lang['antivirus_update_interval'] = '更新间隔';
$lang['antivirus_updates_per_day_invalid'] = '每天升级次数无效。';
