<?php
// Generated by export.php.
$lang['network_broadcast'] = 'Broadcast Address';
$lang['network_connected'] = 'Connected';
$lang['network_connection_status'] = 'Connection Status';
$lang['network_destination'] = 'Destination';
$lang['network_dns_server'] = 'DNS Server';
$lang['network_domain'] = 'Domain';
$lang['network_entire_network'] = 'All Networks';
$lang['network_errmsg_domain_must_have_a_period'] = 'Domain must have at least one period.';
$lang['network_errmsg_hostname_must_have_a_period'] = 'Hostname must have at least one period';
$lang['network_errmsg_port_invalid'] = 'Invalid port number.';
$lang['network_errmsg_port_range_invalid'] = 'Invalid port range.';
$lang['network_errmsg_protocol_invalid'] = 'Invalid protocol.';
$lang['network_errmsg_unusual_gateway_setting'] = 'Your network settings include the following unusual gateway configuration.  Click on help for more information.';
$lang['network_gateway'] = 'Gateway';
$lang['network_hostname'] = 'Hostname';
$lang['network_ip'] = 'IP Address';
$lang['network_ip_range'] = 'IP Address Range';
$lang['network_mac_address'] = 'MAC Address';
$lang['network_mtu'] = 'MTU';
$lang['network_netmask'] = 'Netmask';
$lang['network_network'] = 'Network';
$lang['network_offline'] = 'Offline';
$lang['network_port'] = 'Port';
$lang['network_port_range'] = 'Port Range';
$lang['network_service'] = 'Service';
$lang['network_source'] = 'Source';
$lang['network_waiting_for_connection'] = 'Internet connection is offline';
$lang['network_wins_server'] = 'WINS Server';

$lang['network_interface'] = 'Interface';
$lang['network_alias'] = 'Alias';
// vi: syntax=php ts=4
?>
