<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'Bu yazýlým bir çok dilde kullanýlabilir. Aþaðýdan kullanmak istediðiniz dili seçebilirsiniz.';
$lang['language_app_name'] = 'Dil';
$lang['language_default_system_language'] = 'Varsayýlan Sistem Dili';
$lang['language_keyboard'] = 'Klavye';
$lang['language_keyboard_is_invalid'] = 'Geçersiz Klavye Seçimi.';
$lang['language_language'] = 'Dil';
$lang['language_language_is_invalid'] = 'Seçilen Dil Geçersiz';
$lang['language_update_my_login_session'] = 'Giriþ Oturumumu Güncelle';
