#!/bin/sh

# Initialize base LDAP system
#----------------------------

logger -p local6.notice -t installer "app-ldap-core - initializing core LDAP database"
/usr/sbin/ldap-init

# Set boot policy
#----------------

logger -p local6.notice -t installer "app-ldap-core - enabling core LDAP server"
/sbin/chkconfig slapd on

logger -p local6.notice -t installer "app-ldap-core - starting core LDAP server"
/sbin/service slapd start
