#!/bin/sh

# FIXME: beta hack
/usr/sbin/accounts-init -f
/usr/sbin/samba-init -f
/usr/sbin/ldap-synchronize
/sbin/service auditd restart
/sbin/service nscd start
/sbin/service nslcd start
/sbin/service nscd restart
/sbin/service nslcd restart
