<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['organization_app_description'] = 'Informatie van uw organisatie wordt gebruikt om beveiligings certificaten en andere software instellingen te genereren.';
$lang['organization_app_name'] = 'Organisatie';
$lang['organization_city'] = 'Stad';
$lang['organization_city_invalid'] = 'Ongeldige stad';
$lang['organization_country'] = 'Land';
$lang['organization_country_invalid'] = 'Ongeldig land.';
$lang['organization_organization'] = 'Organisatie';
$lang['organization_organization'] = 'Organisatie';
$lang['organization_organization_invalid'] = 'Ongeldige organisatie';
$lang['organization_postal_code'] = 'Postcode';
$lang['organization_postal_code_invalid'] = 'Ongeldige postcode.';
$lang['organization_region'] = 'Provincie';
$lang['organization_region_invalid'] = 'Ongeldige regio.';
$lang['organization_street_address'] = 'Adres';
$lang['organization_street_address_invalid'] = 'Ongeldig adres.';
$lang['organization_unit'] = 'Afdeling';
$lang['organization_unit_invalid'] = 'Ongeldige afdeling.';
