#!/bin/sh

# Change default template

if [ -e /etc/system/webconfig ]; then
	CHECK=`grep "^template.*standard-5.1" /etc/system/webconfig 2>/dev/null`
	if [ -z "$CHECK" ]; then
		logger -p local6.notice -t installer "app-theme-clearos5x - updating to newer template"
		sed -i -e 's/^template[[:space:]]*=.*/template = standard-5.1/' /etc/system/webconfig
		# Reset login sessions
		rm -f /var/webconfig/tmp/sess_* >/dev/null 2>&1
	fi
fi

# Remove deprecated help URL

CHECK=`grep ^online_help /etc/system/webconfig 2>/dev/null`
if [ -n "$CHECK" ]; then
	logger -p local6.notice -t installer "app-theme-clearos5x - removing deprecated online_help parameter"
	grep -v ^online_help /etc/system/webconfig > /etc/system/webconfig.new
	mv /etc/system/webconfig.new /etc/system/webconfig
fi
