<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_summary'] = 'Waktu dan Tanggal';
$lang['date_app_long_description'] = 'Zona waktu dan alat singkronisasi waktu';
$lang['date_app_tooltip'] = 'VoIP, layanan otentikasi dan aplikasi lainya membutuhkan seting waktu yang tepat, jadi silahkan cek kembali waktu anda dan zona waktu yang benar';
$lang['date_date'] = 'Tanggal';
$lang['date_synchronize_now'] = 'Sinkronisasi sekarang';
$lang['date_time'] = 'Waktu';
$lang['date_time_and_date'] = 'Waktu dan Tanggal';
$lang['date_time_server'] = 'Waktu Server';
$lang['date_time_server_is_invalid'] = 'Waktu server salah.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Jadwal waktu sinkronisasi salah';
$lang['date_time_zone'] = 'Zona Waktu';
$lang['date_time_zone_is_invalid'] = 'Zona waktu salah';
